import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder Firebase configuration generated for all supported platforms.
///
/// Replace the values below with the ones generated by `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'The web platform is not supported in this build. Configure Firebase manually if needed.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'FirebaseOptions have not been configured for ${defaultTargetPlatform.name}.',
        );
    }
  }

  /// Update with the Android values from `google-services.json`.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ANDROID_API_KEY',
    appId: '1:000000000000:android:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'liven-placeholder',
    storageBucket: 'liven-placeholder.appspot.com',
  );

  /// Update with the iOS values from `GoogleService-Info.plist`.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'IOS_API_KEY',
    appId: '1:000000000000:ios:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'liven-placeholder',
    storageBucket: 'liven-placeholder.appspot.com',
    iosBundleId: 'com.app.liven',
  );
}
